global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
